inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'bin/*'
    - 'db/migrate/*'
    - 'db/schema.rb'
    - 'Gemfile'
    - 'Guardfile'
    - 'vendor/**/*'
    - app/controllers/change_requests_controller.rb
    - app/controllers/notes_controller.rb

Metrics/ClassLength:
  Exclude:
    - 'app/controllers/**/*.rb'
    - 'app/models/*.rb'

Metrics/BlockLength:
  Exclude:
    - 'config/routes.rb'
    - 'lib/tasks/**/*.rake'
    - 'spec/**/*.rb'

Documentation:
    Enabled: false
