inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'bin/*'
    - 'db/migrate/*'
    - 'db/schema.rb'
    - 'Gemfile'
    - 'Guardfile'
    - 'vendor/**/*'
    - app/controllers/change_requests_controller.rb
    - app/controllers/notes_controller.rb

Documentation:
    Enabled: false
