sudo: false

language: ruby

services:
  - docker

rvm:
- 2.5.0

cache: bundler

addons:
  postgresql: "9.5"

env:
   global:
    - COMMIT=${TRAVIS_COMMIT::8}
    - SANITIZED_BRANCH=$(echo $TRAVIS_BRANCH|sed 's|/|-|g')
    - REPO=sheltertechsf/askdarcel-api

before_install:
  - nvm install 6
  - nvm use 6
  # Update bundler because of breaking change
  # https://bundler.io/blog/2019/01/04/an-update-on-the-bundler-2-release.html
  - gem install bundler -v '1.17.1'

install:
  # bundle install command copied from Travis's default install.bundler
  - bundle install --jobs=3 --retry=3 --deployment --path=${BUNDLE_PATH:-vendor/bundle}
  - npm install -g newman

before_script:
  - bundle exec rake db:create db:schema:load
  - bundle exec rails swagger

script:
  - bundle exec rake rubocop spec
  - ./travis/postman.sh

after_success:
  - docker build -f Dockerfile -t localimage .
  - |
    echo Pushing Docker image to Docker Hub
    set -eo pipefail
    if [[ -n "$TRAVIS_TAG" || "$SANITIZED_BRANCH" == "master" ]]; then
      DOCKER_IMAGE="$REPO:${TRAVIS_TAG:-latest}"
      docker tag localimage "$DOCKER_IMAGE"
      docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
      docker push "$DOCKER_IMAGE"
    fi
