sudo: false

language: ruby

rvm:
- 2.2.2

cache: bundler

addons:
  # We should be using a newer version (like the latest, 9.5), but
  # this is working out-of-the-box on Travis, so we'll go with it in
  # CI for now.
  postgresql: "9.2"

before_script: bundle exec rake db:create

script: bundle exec rake rubocop db:schema:load spec
