version: "2"
services:
  db:
    image: "postgres:9.5"

  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: rails server --port=3000 --binding=0.0.0.0
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres@db/askdarcel_development
      TEST_DATABASE_URL: postgres://postgres@db/askdarcel_test
      ALGOLIA_APPLICATION_ID:
      ALGOLIA_API_KEY:
      ALGOLIA_INDEX_PREFIX:
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app

  postman:
    build:
      context: .
      dockerfile: Dockerfile.dev.postman
    command: bash -c 'sleep 3 && curl -v http://api:3000/resources?category_id=1 >/dev/null && newman run postman/AskDarcel%20API.postman_collection.json -e postman/docker.postman_environment.json -g postman/globals.postman_globals.json && newman run postman/AskDarcel%20Admin%20API.postman_collection.json -e postman/docker.postman_environment.json -g postman/globals.postman_globals.json'
    depends_on:
      - api
    volumes:
      - .:/usr/src/app
