# This workflow builds and pushes the latest docker image from the master branch
name: publish-latest

on:
  pull_request:
    types: [closed]
    branches:
      - 'master'

env:
  DOCKER_REPO: sheltertechsf

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ env.DOCKER_REPO }}/askdarcel-api:latest
      - run: echo ${{ steps.docker_build.outputs.digest }}
